version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    expose:
      - 5672
      - 15672
    ports:
      - 5672:5672
      - 15672:15672
  cms-db:
    image: mysql/mysql-server:5.7
    container_name: cms-db
    volumes:
      - ./cms-db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: cms
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    expose:
      - "3307"
    ports:
      - "3307:3306"
  cms-web:
    build: ./cms/app
    container_name: cms-web
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./cms/app/:/usr/src/app/
    ports:
      - 8000:8080
    env_file:
      - ./cms/.env.dev
    depends_on:
      - rabbitmq
      - cms-db
  order:
    build: ./order-service
    container_name: order-service
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./order-service/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./order-service/.env.dev
    depends_on:
      - rabbitmq

